# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
#
#
#
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: './Dockerfile'

stages:
- stage: Linting
  displayName: 'Run lint tests'
  jobs:
  - job: python linting
    displayName: linting
    - script: |
       python -m pip install flake8
       flake8 .
- stage: Build
  displayName: 'Build image'
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: ./Dockerfile
        tags: |
          $(tag)
