# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
#
#
#
trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: './Dockerfile'

stages:
- stage: Linting_Build
  displayName: 'Linting & Building Image'
  jobs:
  - job: pythonlinting
    displayName: linting
    steps:
    - script: |
       apt install python3
       apt install python3-pip
       pip3 install flake8
       /usr/local/bin/flake8 .
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: ./Dockerfile
        tags: |
          $(tag)
